image: "python:3.8"

cache:
  paths:
    - ~/.cache/pip

before_script:
  - python --version
  - pip install flake8
  - pip install pylint

stages:
  - Static Analysis
  - Test

flake8:
  stage: Static Analysis
  script:
  - flake8

pylint:
  stage: Static Analysis
  allow_failure: true
  script:
  - pylint spacin/ -d C0114

unittest:
  stage: Test
  script:
    - python -m unittest discover
