image: "python:3.8"

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - Static Analysis
  - Test

flake8:
  stage: Static Analysis
  script:
  - flake8

pylint:
  stage: Static Analysis
  allow_failure: true
  script:
  - pylint

unittest:
  stage: Test
  script:
    - python -m unittest discover -d C0114
