language: python
python:
  - "3.6"
  - "3.8"

install:
  - pip3 install --upgrade pip
  - pip3 install flake8
  - pip3 install pylint
  - pip3 install .

script:
  spacin "hellofriend"

jobs:
  include:
    - stage: "Static Analysis"
      name: "Flake8"
      script: flake8

    - name: "Pylint"
      script: pylint spacin/

    - name: "Unit Testing"
      stage: "unit test"
      script: python -m unittest discover
